name: maquinaJava-usuarios
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Debug secrets
      run: |
        echo "HOST: ${{ secrets.IP_SERVER }}"
        echo "USERNAME: ${{ secrets.USERNAME }}"
        echo "PRIVATE_KEY length: ${#PRIVATE_KEY}"
        echo "PORT: ${{ secrets.PORT }}"
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    - name: Crear carpeta en el servidor
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.IP_SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          mkdir -p /home/ubuntu/usuarios
        debug: true

    - name: Sincronizar archivos
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: "-avz --delete"
        path: "./"
        remote_host: ${{ secrets.IP_SERVER }}
        remote_user: ${{ secrets.USERNAME }}
        remote_path: "/home/ubuntu/usuarios/"
        remote_key: ${{ secrets.PRIVATE_KEY }}
        remote_port: ${{ secrets.PORT }}

    - name: Levantar docker-compose
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.IP_SERVER }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/usuarios
          sudo docker compose up -d --build
        debug: true
